STADTPULS-691 wenn dies dann das story
technologiestiftung/stadtpuls-story-template pull request #14
Opened 2022-02-09 15:43 UTC by ff6347

First draft. See Jira issue for further infos

2022-02-09 17:04 UTC, vogelino requested changes
Great work! I followed the tutorial and it was easy to follow along and it worked well.

I noticed a few things however:
- The images don't load on the deployed versions. Their `src` attributes should include a forward slash for them to work
- There is no link to your story in the root page. In `/src/index.html`, copy a `a.stories-list-item` element and add your story info
- There is still an unwritten section. Search for TBD in your file.
- I would find it better if you author picture was made like all the others. See how to create one in the README file
- You still need to add a custom social-picture for you story. See the README on how to do so and see how it's done in the wrangelkiez story (`src/wrangelkiez/images/social-image.jpg`)

**PS:** I checked neither the grammar nor the writing style as I think that @Esshahn is better suited to take care of this part.

2022-02-09 18:29 UTC, ff6347 commented on src/wenn-dies-dann-das/index.html
> +              <img src="images/new-sensor.png" alt="Interface zum erstellen eines neuen Sensors" />
Wired thing. It worked for me after reloading the page once more. What do you mean by forward slash? ./images/....png right?

2022-02-09 18:34 UTC, vogelino commented on .gitignore
> +src/wenn-dies-dann-das/pandoc.sh
You can use your global or personal configuration for this kind of use cases. The .gitignore has also a documentation dimension to it, so I believe it should remain free from personal configuration. But I'm not too religious about it. Feel free to ignore.

2022-02-09 18:35 UTC, vogelino commented on src/wenn-dies-dann-das/index.html
> +              <img src="images/new-sensor.png" alt="Interface zum erstellen eines neuen Sensors" />
Yes but without the dot. For example: /img/image.png

2022-02-09 19:43 UTC, ff6347 commented on src/wenn-dies-dann-das/index.html
> +              <img src="images/new-sensor.png" alt="Interface zum erstellen eines neuen Sensors" />
But then I have to give the full path. /wenn-dies-dann-dass/images/....png The relative paths should be fine.

2022-02-09 20:08 UTC, vogelino commented on src/wenn-dies-dann-das/index.html
> +              <img src="images/new-sensor.png" alt="Interface zum erstellen eines neuen Sensors" />
Whatever works. Personally it doesn't when I open the vercel preview so something is wrong 😑

2022-02-10 12:53 UTC, ff6347 commented on .gitignore
> +src/wenn-dies-dann-das/pandoc.sh
gone

2022-02-10 12:57 UTC, ff6347 commented on src/wenn-dies-dann-das/index.html
> +            <p>TBD</p>
Done

2022-02-10 13:39 UTC, ff6347 commented
image path is fixed

2022-02-10 15:55 UTC, vogelino commented
Great! Thx for taking my feedback into consideration!

PS: Not that there is still no thumbnail on the overview page of the stories page. Don't forget to add it! :)

2022-02-10 16:12 UTC, vogelino approved these changes

2022-02-14 18:12 UTC, Esshahn commented
can you add your correct twitter?

2022-02-14 18:24 UTC, ff6347 commented
> can you add your correct twitter?

Ähm. I thought I added it. it is https://twitter.com/fmoronzirfas

But I saw that the share links are wrong.

https://github.com/technologiestiftung/stadtpuls-story-template/blob/dacb8c62be8afe81e0484ed1abfab4143b36f318/src/wenn-dies-dann-das/index.html#L516-L542

2022-02-16 16:26 UTC, Esshahn commented
looks great!

2022-02-17 04:56 UTC, ff6347 commented
It is so nice to sit on the sofa while enjoying a coffee and to see how you fix the mess I made. Thanks a lot guys. I'd love to have you listed as co authors.

2022-02-17 08:49 UTC, Esshahn commented
that's what friends are for!

2022-02-24 09:25 UTC, Esshahn approved these changes

2022-02-24 11:02 UTC, merged